### ISSUE TITLE
TImestamp plugin doesn't seem to apply timestamps to messages arriving via Federated exchange before hitting x-consistent-hash exchange

### ISSUE THREAD

**Issue by jefftrimm** [rabbitmq/rabbitmq-message-timestamp#19]
I have a scenario where I have 2 clusters running in two different DC's.  I have a pub-sub exchange federated between both clusters.  On one cluster, I have an x-consistent-hash exchange bound to the pub-sub exchange.  The x-consistent-hash exchange is load balancing across 3 queues, routing on a hash of the "timestamp" property.  If that property isn't set, the x-consistent-hash exchange never delivers the message.

When I publish the message directly onto the pub-sub exchange on local cluster, the timestamp property gets set on the message before it hits the x-consistent-hash exchange and it gets delivered to one of the 3 queues.  When I publish the message on the remote cluster, I see that it federates over to my local pub-sub exchange, but then never gets delivered on the x-consistent-hash exchange.  When I add a 2nd queue directly to the local pub-sub exchange, it does get delivered.

So the symptoms I am seeing is that for federated messages, it doesn't appear to be adding the timestamp header before it hits the  x-consistent hash exchange.

This works:

Publisher --> cluster1 --> pub-sub exchange --> x-consistent-hash (hashing "timestamp" property) --> 1 of 3 target queues

This doesn't work:
Publisher --> cluster 2 --> pub-sub exchange --> federate to Cluster 1 pub-sub-exchange --> x-consistent-hash (hashing "timestamp" property) --> message is lost here, never makes it to target queue

This works (to prove federation to regular queue works without the x-consistent-hash being dependent on the timestamp header):
Publisher --> cluster 2 --> pub-sub exchange --> federate to Cluster 1 pub-sub-exchange --> queue bound to pub sub exchange (see timestamp header on the message).

This also works (to prove federation to x-consistent-hash exchange works that isn't dependent on the timestamp header):
Publisher --> cluster 2 --> pub-sub exchange --> federate to Cluster 1 pub-sub-exchange --> x-consistent-hash (hashing on default "routing key" property) --> 1 of 3 target queues

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
This plugin has no awareness of or dependency on any particular exchange type. It uses the mechanism of channel interceptors, which means a channel on particular node has to observe a `basic.publish` operation in order to time stamp it. With federation it gets a lot more nuanced but there is no dependency on any exchange type (exchanges are nothing more than a module + some routing tables used by channels).

Federation plugin can consume and re-publish a message as a "new one" with an updated set of internally used headers. While I don't why it would affect the timestamp property, telling what exactly is going on without a way to reproduce is quite hard.

If federation, and in particular queue federation is used, I'd recommend making your publishers timestamp messages (yes, which is the purpose of this plugin and this plugin does its job just fine for a high % of use cases). In a clustered scenario, the risks (clocks getting out bf sync by a significant enough margin) would be the same, except the set of nodes would be different (publishers, not RabbitMQ nodes).
