### ISSUE TITLE
Timestamp in nano_seconds

### ISSUE THREAD

**Issue by emerleite** [rabbitmq/rabbitmq-message-timestamp#24]
I use timestamp info to ensure message order. But sometimes I have some issues with collision. What about have an option to use `os:system_time(nano_seconds)` for better precision?

**Comment by michaelklishin** [comment]
The timestamp field in the protocol cannot support that kind of precision. I believe there was a similar suggestion for the core server a few years ago but cannot find it. Using a header is a possible option but there has to be more interest in order to consider it. Your publishers can stamp messages and put it in a header.

Using time for message ordering is tricky even on a single host. I'm not sure if I'd recommend it.
