### ISSUE TITLE
Support RabbitMQ 3.8

### ISSUE THREAD

**Issue by maximusfloydus** [rabbitmq/rabbitmq-message-timestamp#26]
When will a 3.8 compatible version of this plugin be released?

https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.0

**Comment by michaelklishin** [comment]
When the 3.8 version of the community pipeline is ready.

**Comment by michaelklishin** [comment]
Here's a build of this plugin produced against the tip of `master`.  It should be compatible with 3.8:

[rabbitmq_message_timestamp-3.8.0+64.gf34d94d.ez.zip](https://github.com/rabbitmq/rabbitmq-message-timestamp/files/3691185/rabbitmq_message_timestamp-3.8.0%2B64.gf34d94d.ez.zip)

**Comment by lukebakken** [comment]
As a workaround, you have these options:

* Build this plugin from source. First modify [this file](https://github.com/rabbitmq/rabbitmq-message-timestamp/commit/1411de4bbfd0de6461e218598e0663b34e5a24c2) so that the version required is `["3.7.0", "3.8.0"]`. `make dist` will produce the `.ez` file you can put into your `plugins/ ` directory.
* Download the 3.7 compatible plugin. Extract the `.zip` file, and then extract the `.ez` file (it's in zip format as well) into your `plugins/` directory. Edit `plugins/rabbitmq_message_timestamp-20170830-3.7.x/ebin/rabbitmq_message_timestamp.app` to set the versions as I have shown above.

**Comment by michaelklishin** [comment]
Doh, good point. Will rebuild with supported version range updated.

**Comment by michaelklishin** [comment]
[rabbitmq_message_timestamp-3.8.0.+65.g938164c.ez.zip](https://github.com/rabbitmq/rabbitmq-message-timestamp/files/3691195/rabbitmq_message_timestamp-3.8.0.%2B65.g938164c.ez.zip)

**Comment by lukebakken** [comment]
@maximusfloydus - https://github.com/rabbitmq/rabbitmq-message-timestamp/releases/tag/v3.8.0
