### ISSUE TITLE
Can someone build a release?

### ISSUE THREAD

**Issue by eeblouin** [rabbitmq/rabbitmq-message-timestamp#31]
I tried to build a release that includes the latest master (which support v3.9), but I keep running into this make error:

ERLC   rabbit_auth_backend_ldap.erl rabbit_auth_backend_ldap_app.erl rabbit_auth_backend_ldap_util.erl rabbit_log_ldap.erl
/home/eblouin/rabbitmq/rabbitmq-message-timestamp/.erlang.mk/rabbitmq-server/deps/rabbitmq_auth_backend_ldap/include/logging.hrl:1: can't find include lib "rabbit_common/include/logging.hrl"

elixir 1.12.0-rc.1-otp-23
erlang 23.3.4.5
GNU Make 4.2.1

**Comment by binarin** [comment]
No, the same happens to me.

The error is caused by the fact that `rabbit_common` is being git-cloned from an archived `rabbitmq-common` (but other deps are being simlinked from monorepo, you can see it by checking what symlinks are in `deps` after a failed `make`).

If I delete this `rabbit` folder, and replace it with a similar symlink, build goes further. 

    cd deps
    rm -rfv rabbit_common
    ln -s ../.erlang.mk/rabbitmq-server/deps/rabbit_common

But then it break at federation plugin. There the reason is that `deps/rabbit` is now the monorepo, not an an eralng app named `rabbit`. It's actually lives one lever deeper, in `deps/rabbit/deps/rabbit`. And again, by replacing this folder by a symlink I'm able to finally build the plugin:

    cd deps
    rm -rfv rabbit
    ln -s ../.erlang.mk/rabbitmq-server/deps/rabbit

**Comment by binarin** [comment]
https://github.com/rabbitmq/rabbitmq-server/issues/2677#issuecomment-788716478 - this is probably the easiest workaround available currently.

**Comment by binarin** [comment]
Now it works without any workarounds.

**Comment by eeblouin** [comment]
Super-awesome.   I got stuck at the federation build issue too, so I'm glad you sorted it.  Thanks.
